### ISSUE TITLE
set_object_multisite_terms not working when object_id already used for different site

### ISSUE THREAD

**Issue by lsutherl** [HarvardChanSchool/multisite-taxonomies#20]
We have many cases where different blog_ids (site_ids) have the same term and the same post_id (object_id). The function is not setting the term the second time. Query in line 1971 is not specifying blog_id when checking if post already has this term. It continues (without setting) if term is found for post_id regardless of blog_id.

**Comment by guillaumemolter** [comment]
Fixed with #21
