### ISSUE TITLE
how to use this plugin?

### ISSUE THREAD

**Issue by zarankumar** [HarvardChanSchool/multisite-taxonomies#54]
How to install and use this plugin? There is no documentation or readme file. i just installed and trying. But only one menu is available.

**Comment by kalaklanar** [comment]
I'm trying to get the plugin to work, and after install I just get:
"Multisite Taxonomies
No Multisite Taxonomies exist."
There is no way I can figure out how to add taxonomies. Any help would be great.

**Comment by dpegasusm** [comment]
Added some documentation to readme to explain how to register multisite tax
